export class TimesModel {
    constructor(
    private timeId:Date,
    private dayName:string,
    private dayInWeek:number,
    private dayInMonth:number,
    private calendarWeek:number,
    private fiscalWeek:number,
    private weekEndingDay:Date,
    private weekEndingDayId:number,
    private calendarMonth:number,
    private fiscalMonth:number,
    private calendarMonthDesc:string,
    private calendarMonthId:number,
    private fiscalMonthDesc:string,
    private fiscalMonthId:number,
    private daysInCalMonth:number,
    private daysInFsMonth:number,
    private endOfCalMonth:Date,
    private endOfFisMonth:Date,
    private calendarMonthName:string,
    private fiscalMonthName:string,
    private calendarQuarterDesc:string,
    private calendarQuarterId:number,
    private fiscalQuarterDesc:string,
    private fiscalQuarterId:number,
    private daysInCalQuarter:number,
    private daysInFisQuarter:number,
    private endOfCalQuarter:Date,
    private endOfFisQuarter:Date,
    private calendarQuarterInt:number,
    private fiscalQuarterInt:number,
    private year:number,
    ){}
}
