export class TimesModel {
    constructor(
    public timeId:Date,
    public dayName:string,
    public dayInWeek:number,
    public dayInMonth:number,
    public calendarWeek:number,
    public fiscalWeek:number,
    public weekEndingDay:Date,
    public weekEndingDayId:number,
    public calendarMonth:number,
    public fiscalMonth:number,
    public calendarMonthDesc:string,
    public calendarMonthId:number,
    public fiscalMonthDesc:string,
    public fiscalMonthId:number,
    public daysInCalMonth:number,
    public daysInFsMonth:number,
    public endOfCalMonth:Date,
    public endOfFisMonth:Date,
    public calendarMonthName:string,
    public fiscalMonthName:string,
    public calendarQuarterDesc:string,
    public calendarQuarterId:number,
    public fiscalQuarterDesc:string,
    public fiscalQuarterId:number,
    public daysInCalQuarter:number,
    public daysInFisQuarter:number,
    public endOfCalQuarter:Date,
    public endOfFisQuarter:Date,
    public calendarQuarterInt:number,
    public fiscalQuarterInt:number,
    public year:number,
    ){}
}
